name: build_package_rpi

on:
  push:
    branches: [ 2.3-evo ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        overprovision-lvm: 'true'
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: pguyot/arm-runner-action@v2.5.2
      id: build_image
      with:
        base_image: raspios_lite:latest
        image_additional_mb: 4000
        copy_repository_path: /opt
        copy_artifact_path: gstreamer-latest
        import_github_env: true
        commands: |
            ls -a
            cd /opt
            cd gstreamer-latest
            apt update
            curl -1sLf 'https://dl.cloudsmith.io/public/openhd/openhd-2-3-evo/setup.deb.sh' | sudo -E bash
            sudo bash install_dep.sh
            touch /etc/ld.so.conf.d/qt.conf
            echo "/opt/Qt5.15.4/lib/" >/etc/ld.so.conf.d/qt.conf
            sudo ldconfig
            export PATH="$PATH:/opt/Qt5.15.4/bin/"
            rm -Rf /usr/bin/qmake
            sudo ln -s /opt/Qt5.15.4/bin/qmake /usr/bin/qmake
            export PATH="$PATH:/opt/Qt5.15.4/bin/"
            meson --prefix=/tmp/gst-plugins-good/usr -Dbad=disabled -Dlibav=disabled -Dugly=disabled -Dgood=disabled build            
            ninja -C build
            ninja -C build install
            cd subprojects/gst-plugins-good/
            meson --prefix=/tmp/gst-plugins-good/usr -Drpicamsrc=enabled -Dqt5=enabled build
            ninja -C build
            ninja -C build install
            # sudo cp libgstqmlgl.so ../
            # sudo cp libgstrpicamsrc.so ../ 
            # sudo mv ../libgstqmlgl.so .
            # sudo mv ../libgstrpicamsrc.so .
            fpm -a armhf -s dir -t deb -n gst-plugins-good -v 2.3-evo -C /tmp/gst-plugins-good -p gst-plugins-good-2.3-evo.deb
            ls -a


    - name: Upload to Github
      uses: 'actions/upload-artifact@v2'
      with:
        name: "gst-plugins-good"
        path: |
          gst-plugins-good/*.deb
          
    - name: Push
      id: push
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: "push"
        format: "deb"
        owner: "openhd"
        repo: "openhd-2-3-evo-dev"
        distro: "raspbian"
        release: "bullseye"
        republish: "true" # needed ONLY if version is not changing
        file: "gst-plugins-good/*.deb"
          
      #- name: Install
      #  run: |
      #    cd OpenHD/build
      #    sudo cmake --install .
      #- name: Build ninja
      #  run: |
      #    sudo apt -y install ninja-build
      #    cd OpenHD
      #    ./build_cmake.sh
